// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: balance/balance.proto

package balance

import (
	pagination_balance "github.com/djoonta/kpbalanceproto/pagination_balance"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          string               `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	PendingAmount float64              `protobuf:"fixed64,3,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	Amount        float64              `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	FromId        string               `protobuf:"bytes,5,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromBalance   float64              `protobuf:"fixed64,6,opt,name=from_balance,json=fromBalance,proto3" json:"from_balance,omitempty"`
	ToId          string               `protobuf:"bytes,7,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ToBalance     float64              `protobuf:"fixed64,8,opt,name=to_balance,json=toBalance,proto3" json:"to_balance,omitempty"`
	Status        string               `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FromLast      float64              `protobuf:"fixed64,12,opt,name=from_last,json=fromLast,proto3" json:"from_last,omitempty"`
	ToLast        float64              `protobuf:"fixed64,13,opt,name=to_last,json=toLast,proto3" json:"to_last,omitempty"`
	Type          string               `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BalanceInfo) Reset() {
	*x = BalanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceInfo) ProtoMessage() {}

func (x *BalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceInfo.ProtoReflect.Descriptor instead.
func (*BalanceInfo) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalanceInfo) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *BalanceInfo) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *BalanceInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceInfo) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BalanceInfo) GetFromBalance() float64 {
	if x != nil {
		return x.FromBalance
	}
	return 0
}

func (x *BalanceInfo) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *BalanceInfo) GetToBalance() float64 {
	if x != nil {
		return x.ToBalance
	}
	return 0
}

func (x *BalanceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BalanceInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BalanceInfo) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *BalanceInfo) GetFromLast() float64 {
	if x != nil {
		return x.FromLast
	}
	return 0
}

func (x *BalanceInfo) GetToLast() float64 {
	if x != nil {
		return x.ToLast
	}
	return 0
}

func (x *BalanceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BalanceFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BalanceFindIDRequest) Reset() {
	*x = BalanceFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceFindIDRequest) ProtoMessage() {}

func (x *BalanceFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceFindIDRequest.ProtoReflect.Descriptor instead.
func (*BalanceFindIDRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BalanceFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance *BalanceInfo `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *BalanceFindIDResponse) Reset() {
	*x = BalanceFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceFindIDResponse) ProtoMessage() {}

func (x *BalanceFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceFindIDResponse.ProtoReflect.Descriptor instead.
func (*BalanceFindIDResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceFindIDResponse) GetBalance() *BalanceInfo {
	if x != nil {
		return x.Balance
	}
	return nil
}

type BalanceFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *BalanceFindAllRequest) Reset() {
	*x = BalanceFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceFindAllRequest) ProtoMessage() {}

func (x *BalanceFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceFindAllRequest.ProtoReflect.Descriptor instead.
func (*BalanceFindAllRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceFindAllRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *BalanceFindAllRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type BalanceFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balances   []*BalanceInfo                     `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	Pagination *pagination_balance.PaginationInfo `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *BalanceFindAllResponse) Reset() {
	*x = BalanceFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceFindAllResponse) ProtoMessage() {}

func (x *BalanceFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceFindAllResponse.ProtoReflect.Descriptor instead.
func (*BalanceFindAllResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{4}
}

func (x *BalanceFindAllResponse) GetBalances() []*BalanceInfo {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *BalanceFindAllResponse) GetPagination() *pagination_balance.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type BalanceWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messsage string `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
}

func (x *BalanceWriteResponse) Reset() {
	*x = BalanceWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceWriteResponse) ProtoMessage() {}

func (x *BalanceWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceWriteResponse.ProtoReflect.Descriptor instead.
func (*BalanceWriteResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BalanceWriteResponse) GetMesssage() string {
	if x != nil {
		return x.Messsage
	}
	return ""
}

type BalanceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Note          string  `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	PendingAmount float64 `protobuf:"fixed64,2,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	Amount        float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	FromId        string  `protobuf:"bytes,4,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromBalance   float64 `protobuf:"fixed64,5,opt,name=from_balance,json=fromBalance,proto3" json:"from_balance,omitempty"`
	ToId          string  `protobuf:"bytes,6,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ToBalance     float64 `protobuf:"fixed64,7,opt,name=to_balance,json=toBalance,proto3" json:"to_balance,omitempty"`
	Status        string  `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	FromLast      float64 `protobuf:"fixed64,9,opt,name=from_last,json=fromLast,proto3" json:"from_last,omitempty"`
	ToLast        float64 `protobuf:"fixed64,10,opt,name=to_last,json=toLast,proto3" json:"to_last,omitempty"`
	Type          string  `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BalanceCreateRequest) Reset() {
	*x = BalanceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceCreateRequest) ProtoMessage() {}

func (x *BalanceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceCreateRequest.ProtoReflect.Descriptor instead.
func (*BalanceCreateRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceCreateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *BalanceCreateRequest) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *BalanceCreateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceCreateRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BalanceCreateRequest) GetFromBalance() float64 {
	if x != nil {
		return x.FromBalance
	}
	return 0
}

func (x *BalanceCreateRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *BalanceCreateRequest) GetToBalance() float64 {
	if x != nil {
		return x.ToBalance
	}
	return 0
}

func (x *BalanceCreateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BalanceCreateRequest) GetFromLast() float64 {
	if x != nil {
		return x.FromLast
	}
	return 0
}

func (x *BalanceCreateRequest) GetToLast() float64 {
	if x != nil {
		return x.ToLast
	}
	return 0
}

func (x *BalanceCreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BalanceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateResponse *BalanceWriteResponse `protobuf:"bytes,1,opt,name=create_response,json=createResponse,proto3" json:"create_response,omitempty"`
}

func (x *BalanceCreateResponse) Reset() {
	*x = BalanceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceCreateResponse) ProtoMessage() {}

func (x *BalanceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceCreateResponse.ProtoReflect.Descriptor instead.
func (*BalanceCreateResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceCreateResponse) GetCreateResponse() *BalanceWriteResponse {
	if x != nil {
		return x.CreateResponse
	}
	return nil
}

type BalanceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BalanceDeleteRequest) Reset() {
	*x = BalanceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDeleteRequest) ProtoMessage() {}

func (x *BalanceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDeleteRequest.ProtoReflect.Descriptor instead.
func (*BalanceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{8}
}

func (x *BalanceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BalanceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteResponse *BalanceWriteResponse `protobuf:"bytes,1,opt,name=delete_response,json=deleteResponse,proto3" json:"delete_response,omitempty"`
}

func (x *BalanceDeleteResponse) Reset() {
	*x = BalanceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceDeleteResponse) ProtoMessage() {}

func (x *BalanceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceDeleteResponse.ProtoReflect.Descriptor instead.
func (*BalanceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{9}
}

func (x *BalanceDeleteResponse) GetDeleteResponse() *BalanceWriteResponse {
	if x != nil {
		return x.DeleteResponse
	}
	return nil
}

type BalanceUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          string  `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	PendingAmount float64 `protobuf:"fixed64,3,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	Amount        float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	FromId        string  `protobuf:"bytes,5,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromBalance   float64 `protobuf:"fixed64,6,opt,name=from_balance,json=fromBalance,proto3" json:"from_balance,omitempty"`
	ToId          string  `protobuf:"bytes,7,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ToBalance     float64 `protobuf:"fixed64,8,opt,name=to_balance,json=toBalance,proto3" json:"to_balance,omitempty"`
	Status        string  `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	FromLast      float64 `protobuf:"fixed64,10,opt,name=from_last,json=fromLast,proto3" json:"from_last,omitempty"`
	ToLast        float64 `protobuf:"fixed64,11,opt,name=to_last,json=toLast,proto3" json:"to_last,omitempty"`
	Type          string  `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BalanceUpdateRequest) Reset() {
	*x = BalanceUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdateRequest) ProtoMessage() {}

func (x *BalanceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdateRequest.ProtoReflect.Descriptor instead.
func (*BalanceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalanceUpdateRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *BalanceUpdateRequest) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *BalanceUpdateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BalanceUpdateRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *BalanceUpdateRequest) GetFromBalance() float64 {
	if x != nil {
		return x.FromBalance
	}
	return 0
}

func (x *BalanceUpdateRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *BalanceUpdateRequest) GetToBalance() float64 {
	if x != nil {
		return x.ToBalance
	}
	return 0
}

func (x *BalanceUpdateRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BalanceUpdateRequest) GetFromLast() float64 {
	if x != nil {
		return x.FromLast
	}
	return 0
}

func (x *BalanceUpdateRequest) GetToLast() float64 {
	if x != nil {
		return x.ToLast
	}
	return 0
}

func (x *BalanceUpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BalanceUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateResponse *BalanceWriteResponse `protobuf:"bytes,1,opt,name=update_response,json=updateResponse,proto3" json:"update_response,omitempty"`
}

func (x *BalanceUpdateResponse) Reset() {
	*x = BalanceUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_balance_balance_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdateResponse) ProtoMessage() {}

func (x *BalanceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_balance_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdateResponse.ProtoReflect.Descriptor instead.
func (*BalanceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_balance_balance_proto_rawDescGZIP(), []int{11}
}

func (x *BalanceUpdateResponse) GetUpdateResponse() *BalanceWriteResponse {
	if x != nil {
		return x.UpdateResponse
	}
	return nil
}

var File_balance_balance_proto protoreflect.FileDescriptor

var file_balance_balance_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x03, 0x0a, 0x0b, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74,
	0x6f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6c,
	0x61, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4c,
	0x61, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x74, 0x6f, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x26, 0x0a, 0x14, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x15, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x35, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x15, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x16,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12,
	0x3e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x4c, 0x0a, 0x14, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xbb, 0x02,
	0x0a, 0x14, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x74, 0x6f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x74, 0x6f, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x66, 0x0a, 0x15, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x66, 0x0a, 0x15, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0xcb, 0x02, 0x0a, 0x14, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b,
	0x66, 0x72, 0x6f, 0x6d, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x74,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x6f, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x6c, 0x61, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x4c, 0x61, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x74, 0x6f, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x66, 0x0a, 0x15, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x6f, 0x6f, 0x6e, 0x74, 0x61, 0x2f,
	0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_balance_balance_proto_rawDescOnce sync.Once
	file_balance_balance_proto_rawDescData = file_balance_balance_proto_rawDesc
)

func file_balance_balance_proto_rawDescGZIP() []byte {
	file_balance_balance_proto_rawDescOnce.Do(func() {
		file_balance_balance_proto_rawDescData = protoimpl.X.CompressGZIP(file_balance_balance_proto_rawDescData)
	})
	return file_balance_balance_proto_rawDescData
}

var file_balance_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_balance_balance_proto_goTypes = []interface{}{
	(*BalanceInfo)(nil),                       // 0: kpbalanceproto.BalanceInfo
	(*BalanceFindIDRequest)(nil),              // 1: kpbalanceproto.BalanceFindIDRequest
	(*BalanceFindIDResponse)(nil),             // 2: kpbalanceproto.BalanceFindIDResponse
	(*BalanceFindAllRequest)(nil),             // 3: kpbalanceproto.BalanceFindAllRequest
	(*BalanceFindAllResponse)(nil),            // 4: kpbalanceproto.BalanceFindAllResponse
	(*BalanceWriteResponse)(nil),              // 5: kpbalanceproto.BalanceWriteResponse
	(*BalanceCreateRequest)(nil),              // 6: kpbalanceproto.BalanceCreateRequest
	(*BalanceCreateResponse)(nil),             // 7: kpbalanceproto.BalanceCreateResponse
	(*BalanceDeleteRequest)(nil),              // 8: kpbalanceproto.BalanceDeleteRequest
	(*BalanceDeleteResponse)(nil),             // 9: kpbalanceproto.BalanceDeleteResponse
	(*BalanceUpdateRequest)(nil),              // 10: kpbalanceproto.BalanceUpdateRequest
	(*BalanceUpdateResponse)(nil),             // 11: kpbalanceproto.BalanceUpdateResponse
	(*timestamp.Timestamp)(nil),               // 12: google.protobuf.Timestamp
	(*pagination_balance.PaginationInfo)(nil), // 13: kpbalanceproto.PaginationInfo
}
var file_balance_balance_proto_depIdxs = []int32{
	12, // 0: kpbalanceproto.BalanceInfo.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: kpbalanceproto.BalanceInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: kpbalanceproto.BalanceFindIDResponse.balance:type_name -> kpbalanceproto.BalanceInfo
	0,  // 3: kpbalanceproto.BalanceFindAllResponse.balances:type_name -> kpbalanceproto.BalanceInfo
	13, // 4: kpbalanceproto.BalanceFindAllResponse.pagination:type_name -> kpbalanceproto.PaginationInfo
	5,  // 5: kpbalanceproto.BalanceCreateResponse.create_response:type_name -> kpbalanceproto.BalanceWriteResponse
	5,  // 6: kpbalanceproto.BalanceDeleteResponse.delete_response:type_name -> kpbalanceproto.BalanceWriteResponse
	5,  // 7: kpbalanceproto.BalanceUpdateResponse.update_response:type_name -> kpbalanceproto.BalanceWriteResponse
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_balance_balance_proto_init() }
func file_balance_balance_proto_init() {
	if File_balance_balance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_balance_balance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_balance_balance_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_balance_balance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_balance_balance_proto_goTypes,
		DependencyIndexes: file_balance_balance_proto_depIdxs,
		MessageInfos:      file_balance_balance_proto_msgTypes,
	}.Build()
	File_balance_balance_proto = out.File
	file_balance_balance_proto_rawDesc = nil
	file_balance_balance_proto_goTypes = nil
	file_balance_balance_proto_depIdxs = nil
}
