// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: withdrawl/withdrawl.proto

package withdrawl

import (
	pagination_balance "github.com/djoonta/kpbalanceproto/pagination_balance"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawlInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BalanceId      string               `protobuf:"bytes,2,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
	Vendor         string               `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	BankAccountId  string               `protobuf:"bytes,5,opt,name=bank_account_id,json=bankAccountId,proto3" json:"bank_account_id,omitempty"`
	Amount         float64              `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Verified       bool                 `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	CreatedAt      *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TellerId       string               `protobuf:"bytes,10,opt,name=teller_id,json=tellerId,proto3" json:"teller_id,omitempty"`
	VerifiedById   string               `protobuf:"bytes,11,opt,name=verified_by_id,json=verifiedById,proto3" json:"verified_by_id,omitempty"`
	Type           string               `protobuf:"bytes,12,opt,name=type,proto3" json:"type,omitempty"`
	BankName       string               `protobuf:"bytes,13,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankCode       string               `protobuf:"bytes,14,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	BankSwifthCode string               `protobuf:"bytes,15,opt,name=bank_swifth_code,json=bankSwifthCode,proto3" json:"bank_swifth_code,omitempty"`
}

func (x *WithdrawlInfo) Reset() {
	*x = WithdrawlInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlInfo) ProtoMessage() {}

func (x *WithdrawlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlInfo.ProtoReflect.Descriptor instead.
func (*WithdrawlInfo) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{0}
}

func (x *WithdrawlInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawlInfo) GetBalanceId() string {
	if x != nil {
		return x.BalanceId
	}
	return ""
}

func (x *WithdrawlInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *WithdrawlInfo) GetBankAccountId() string {
	if x != nil {
		return x.BankAccountId
	}
	return ""
}

func (x *WithdrawlInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawlInfo) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *WithdrawlInfo) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WithdrawlInfo) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WithdrawlInfo) GetTellerId() string {
	if x != nil {
		return x.TellerId
	}
	return ""
}

func (x *WithdrawlInfo) GetVerifiedById() string {
	if x != nil {
		return x.VerifiedById
	}
	return ""
}

func (x *WithdrawlInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WithdrawlInfo) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *WithdrawlInfo) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *WithdrawlInfo) GetBankSwifthCode() string {
	if x != nil {
		return x.BankSwifthCode
	}
	return ""
}

type WithdrawlFindIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WithdrawlFindIDRequest) Reset() {
	*x = WithdrawlFindIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlFindIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlFindIDRequest) ProtoMessage() {}

func (x *WithdrawlFindIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlFindIDRequest.ProtoReflect.Descriptor instead.
func (*WithdrawlFindIDRequest) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawlFindIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WithdrawlFindIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Withdrawl *WithdrawlInfo `protobuf:"bytes,1,opt,name=withdrawl,proto3" json:"withdrawl,omitempty"`
}

func (x *WithdrawlFindIDResponse) Reset() {
	*x = WithdrawlFindIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlFindIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlFindIDResponse) ProtoMessage() {}

func (x *WithdrawlFindIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlFindIDResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlFindIDResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{2}
}

func (x *WithdrawlFindIDResponse) GetWithdrawl() *WithdrawlInfo {
	if x != nil {
		return x.Withdrawl
	}
	return nil
}

type WithdrawlFindAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit string `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *WithdrawlFindAllRequest) Reset() {
	*x = WithdrawlFindAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlFindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlFindAllRequest) ProtoMessage() {}

func (x *WithdrawlFindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlFindAllRequest.ProtoReflect.Descriptor instead.
func (*WithdrawlFindAllRequest) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawlFindAllRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *WithdrawlFindAllRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type WithdrawlFindAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Withdrawls []*WithdrawlInfo                   `protobuf:"bytes,1,rep,name=withdrawls,proto3" json:"withdrawls,omitempty"`
	Pagination *pagination_balance.PaginationInfo `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *WithdrawlFindAllResponse) Reset() {
	*x = WithdrawlFindAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlFindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlFindAllResponse) ProtoMessage() {}

func (x *WithdrawlFindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlFindAllResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlFindAllResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawlFindAllResponse) GetWithdrawls() []*WithdrawlInfo {
	if x != nil {
		return x.Withdrawls
	}
	return nil
}

func (x *WithdrawlFindAllResponse) GetPagination() *pagination_balance.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type WithdrawlWriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messsage string `protobuf:"bytes,2,opt,name=messsage,proto3" json:"messsage,omitempty"`
}

func (x *WithdrawlWriteResponse) Reset() {
	*x = WithdrawlWriteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlWriteResponse) ProtoMessage() {}

func (x *WithdrawlWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlWriteResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlWriteResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawlWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawlWriteResponse) GetMesssage() string {
	if x != nil {
		return x.Messsage
	}
	return ""
}

type WithdrawlCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BalanceId     string  `protobuf:"bytes,1,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
	Vendor        string  `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	BankAccountId string  `protobuf:"bytes,3,opt,name=bank_account_id,json=bankAccountId,proto3" json:"bank_account_id,omitempty"`
	Amount        float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Verified      bool    `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	TellerId      string  `protobuf:"bytes,6,opt,name=teller_id,json=tellerId,proto3" json:"teller_id,omitempty"`
	VerifiedById  string  `protobuf:"bytes,7,opt,name=verified_by_id,json=verifiedById,proto3" json:"verified_by_id,omitempty"`
	Type          string  `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithdrawlCreateRequest) Reset() {
	*x = WithdrawlCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlCreateRequest) ProtoMessage() {}

func (x *WithdrawlCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlCreateRequest.ProtoReflect.Descriptor instead.
func (*WithdrawlCreateRequest) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawlCreateRequest) GetBalanceId() string {
	if x != nil {
		return x.BalanceId
	}
	return ""
}

func (x *WithdrawlCreateRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *WithdrawlCreateRequest) GetBankAccountId() string {
	if x != nil {
		return x.BankAccountId
	}
	return ""
}

func (x *WithdrawlCreateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawlCreateRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *WithdrawlCreateRequest) GetTellerId() string {
	if x != nil {
		return x.TellerId
	}
	return ""
}

func (x *WithdrawlCreateRequest) GetVerifiedById() string {
	if x != nil {
		return x.VerifiedById
	}
	return ""
}

func (x *WithdrawlCreateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithdrawlCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateResponse *WithdrawlWriteResponse `protobuf:"bytes,1,opt,name=create_response,json=createResponse,proto3" json:"create_response,omitempty"`
}

func (x *WithdrawlCreateResponse) Reset() {
	*x = WithdrawlCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlCreateResponse) ProtoMessage() {}

func (x *WithdrawlCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlCreateResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlCreateResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawlCreateResponse) GetCreateResponse() *WithdrawlWriteResponse {
	if x != nil {
		return x.CreateResponse
	}
	return nil
}

type WithdrawlDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WithdrawlDeleteRequest) Reset() {
	*x = WithdrawlDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlDeleteRequest) ProtoMessage() {}

func (x *WithdrawlDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlDeleteRequest.ProtoReflect.Descriptor instead.
func (*WithdrawlDeleteRequest) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawlDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WithdrawlDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeleteResponse *WithdrawlWriteResponse `protobuf:"bytes,1,opt,name=delete_response,json=deleteResponse,proto3" json:"delete_response,omitempty"`
}

func (x *WithdrawlDeleteResponse) Reset() {
	*x = WithdrawlDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlDeleteResponse) ProtoMessage() {}

func (x *WithdrawlDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlDeleteResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlDeleteResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawlDeleteResponse) GetDeleteResponse() *WithdrawlWriteResponse {
	if x != nil {
		return x.DeleteResponse
	}
	return nil
}

type WithdrawlUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BalanceId     string  `protobuf:"bytes,2,opt,name=balance_id,json=balanceId,proto3" json:"balance_id,omitempty"`
	Vendor        string  `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	BankAccountId string  `protobuf:"bytes,5,opt,name=bank_account_id,json=bankAccountId,proto3" json:"bank_account_id,omitempty"`
	Amount        float64 `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Verified      bool    `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	TellerId      string  `protobuf:"bytes,8,opt,name=teller_id,json=tellerId,proto3" json:"teller_id,omitempty"`
	VerifiedById  string  `protobuf:"bytes,9,opt,name=verified_by_id,json=verifiedById,proto3" json:"verified_by_id,omitempty"`
	Type          string  `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WithdrawlUpdateRequest) Reset() {
	*x = WithdrawlUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlUpdateRequest) ProtoMessage() {}

func (x *WithdrawlUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlUpdateRequest.ProtoReflect.Descriptor instead.
func (*WithdrawlUpdateRequest) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawlUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetBalanceId() string {
	if x != nil {
		return x.BalanceId
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetBankAccountId() string {
	if x != nil {
		return x.BankAccountId
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawlUpdateRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *WithdrawlUpdateRequest) GetTellerId() string {
	if x != nil {
		return x.TellerId
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetVerifiedById() string {
	if x != nil {
		return x.VerifiedById
	}
	return ""
}

func (x *WithdrawlUpdateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type WithdrawlUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateResponse *WithdrawlWriteResponse `protobuf:"bytes,1,opt,name=update_response,json=updateResponse,proto3" json:"update_response,omitempty"`
}

func (x *WithdrawlUpdateResponse) Reset() {
	*x = WithdrawlUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdrawl_withdrawl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawlUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawlUpdateResponse) ProtoMessage() {}

func (x *WithdrawlUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdrawl_withdrawl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawlUpdateResponse.ProtoReflect.Descriptor instead.
func (*WithdrawlUpdateResponse) Descriptor() ([]byte, []int) {
	return file_withdrawl_withdrawl_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawlUpdateResponse) GetUpdateResponse() *WithdrawlWriteResponse {
	if x != nil {
		return x.UpdateResponse
	}
	return nil
}

var File_withdrawl_withdrawl_proto protoreflect.FileDescriptor

var file_withdrawl_withdrawl_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x2f, 0x77, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6b, 0x70, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x03, 0x0a, 0x0d, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x6e,
	0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x62, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6b,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x73, 0x77,
	0x69, 0x66, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x62, 0x61, 0x6e, 0x6b, 0x53, 0x77, 0x69, 0x66, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x28, 0x0a, 0x16, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x46, 0x69, 0x6e, 0x64,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x17, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x46, 0x69, 0x6e, 0x64, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x6c, 0x22, 0x43, 0x0a, 0x17, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x99, 0x01, 0x0a, 0x18, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x6c, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x6c, 0x73, 0x12, 0x3e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x16, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x82, 0x02, 0x0a, 0x16, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62,
	0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6a, 0x0a, 0x17, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6b, 0x70,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6a, 0x0a,
	0x17, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x92, 0x02, 0x0a, 0x16, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x62,
	0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6a,
	0x0a, 0x17, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x6f, 0x6f, 0x6e, 0x74, 0x61,
	0x2f, 0x6b, 0x70, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_withdrawl_withdrawl_proto_rawDescOnce sync.Once
	file_withdrawl_withdrawl_proto_rawDescData = file_withdrawl_withdrawl_proto_rawDesc
)

func file_withdrawl_withdrawl_proto_rawDescGZIP() []byte {
	file_withdrawl_withdrawl_proto_rawDescOnce.Do(func() {
		file_withdrawl_withdrawl_proto_rawDescData = protoimpl.X.CompressGZIP(file_withdrawl_withdrawl_proto_rawDescData)
	})
	return file_withdrawl_withdrawl_proto_rawDescData
}

var file_withdrawl_withdrawl_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_withdrawl_withdrawl_proto_goTypes = []interface{}{
	(*WithdrawlInfo)(nil),                     // 0: kpbalanceproto.WithdrawlInfo
	(*WithdrawlFindIDRequest)(nil),            // 1: kpbalanceproto.WithdrawlFindIDRequest
	(*WithdrawlFindIDResponse)(nil),           // 2: kpbalanceproto.WithdrawlFindIDResponse
	(*WithdrawlFindAllRequest)(nil),           // 3: kpbalanceproto.WithdrawlFindAllRequest
	(*WithdrawlFindAllResponse)(nil),          // 4: kpbalanceproto.WithdrawlFindAllResponse
	(*WithdrawlWriteResponse)(nil),            // 5: kpbalanceproto.WithdrawlWriteResponse
	(*WithdrawlCreateRequest)(nil),            // 6: kpbalanceproto.WithdrawlCreateRequest
	(*WithdrawlCreateResponse)(nil),           // 7: kpbalanceproto.WithdrawlCreateResponse
	(*WithdrawlDeleteRequest)(nil),            // 8: kpbalanceproto.WithdrawlDeleteRequest
	(*WithdrawlDeleteResponse)(nil),           // 9: kpbalanceproto.WithdrawlDeleteResponse
	(*WithdrawlUpdateRequest)(nil),            // 10: kpbalanceproto.WithdrawlUpdateRequest
	(*WithdrawlUpdateResponse)(nil),           // 11: kpbalanceproto.WithdrawlUpdateResponse
	(*timestamp.Timestamp)(nil),               // 12: google.protobuf.Timestamp
	(*pagination_balance.PaginationInfo)(nil), // 13: kpbalanceproto.PaginationInfo
}
var file_withdrawl_withdrawl_proto_depIdxs = []int32{
	12, // 0: kpbalanceproto.WithdrawlInfo.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: kpbalanceproto.WithdrawlInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: kpbalanceproto.WithdrawlFindIDResponse.withdrawl:type_name -> kpbalanceproto.WithdrawlInfo
	0,  // 3: kpbalanceproto.WithdrawlFindAllResponse.withdrawls:type_name -> kpbalanceproto.WithdrawlInfo
	13, // 4: kpbalanceproto.WithdrawlFindAllResponse.pagination:type_name -> kpbalanceproto.PaginationInfo
	5,  // 5: kpbalanceproto.WithdrawlCreateResponse.create_response:type_name -> kpbalanceproto.WithdrawlWriteResponse
	5,  // 6: kpbalanceproto.WithdrawlDeleteResponse.delete_response:type_name -> kpbalanceproto.WithdrawlWriteResponse
	5,  // 7: kpbalanceproto.WithdrawlUpdateResponse.update_response:type_name -> kpbalanceproto.WithdrawlWriteResponse
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_withdrawl_withdrawl_proto_init() }
func file_withdrawl_withdrawl_proto_init() {
	if File_withdrawl_withdrawl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_withdrawl_withdrawl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlFindIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlFindIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlFindAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlFindAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlWriteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdrawl_withdrawl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawlUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_withdrawl_withdrawl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_withdrawl_withdrawl_proto_goTypes,
		DependencyIndexes: file_withdrawl_withdrawl_proto_depIdxs,
		MessageInfos:      file_withdrawl_withdrawl_proto_msgTypes,
	}.Build()
	File_withdrawl_withdrawl_proto = out.File
	file_withdrawl_withdrawl_proto_rawDesc = nil
	file_withdrawl_withdrawl_proto_goTypes = nil
	file_withdrawl_withdrawl_proto_depIdxs = nil
}
